### ISSUE TITLE
Reminder about currency on the admin page

### ISSUE THREAD

**Issue by tilsammans** [Sign2Pay/magento-sign2pay#7]
We got feedback:

Downloaded sign2pay extension but it did not show up on checkout page. It was because of the currency limitation. I had installed Magento with American locale. Anyways I added a "return true" statement in the currency check method as a workaround. So don't be surprised if you go to checkout page and see it working with USD. Maybe you can consider putting a notification on the admin side, which reminds about the currency.

**Comment by magently** [comment]
-- Please reply above this line --


Hello,

We are sorry, but we are not sure if we understand this feedback. As
far as we know you only accept EUR so it cannot be used for USD. 

Best,
-- 
Tadeusz Rolski,
Magently

**Comment by tilsammans** [comment]
You can write a reminder on the admin side, right? That is all. I agree that we only support EUR.

Op 23 sep. 2015 om 18:45 heeft magently <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

-- Please reply above this line --


Hello,

We are sorry, but we are not sure if we understand this feedback. As
far as we know you only accept EUR so it cannot be used for USD.

Best,
--
Tadeusz Rolski,
Magently





> On Fri, Sep 18, 2015 at 2:20 PM CEST, Sign2Pay/magento-Sign2Pay &lt;reply@reply.github.com<mailto:reply@reply.github.com>&gt; wrote:
>
> Assigned #7 [1] to @magently [2].
>
> -
> Reply to this email directly or view it on GitHub [3].
>
> Links:
> ------
> [1] https://github.com/Sign2Pay/magento-sign2pay/issues/7
> [2] https://github.com/magently
> [3]
> https://github.com/Sign2Pay/magento-sign2pay/issues/7#event-413161471
>
>
>
>> On Fri, Sep 18, 2015 at 2:18 PM CEST, Sign2Pay/magento-Sign2Pay &lt;reply@reply.github.com<mailto:reply@reply.github.com>&gt; wrote:
>>
>>
>>
>> We got feedback:
>>
>> Downloaded sign2pay extension but it did not show up on checkout
>> page. It was because of the currency limitation. I had installed
>> Magento with American locale. Anyways I added a "return true"
>> statement in the currency check method as a workaround. So don't be
>> surprised if you go to checkout page and see it working with USD.
>> Maybe you can consider putting a notification on the admin side, which
>> reminds about the currency.
>>
>> -
>> Reply to this email directly or view it on GitHub [1].
>>
>> Links:
>> ------
>> [1] https://github.com/Sign2Pay/magento-sign2pay/issues/7
>>
>>
>>
>>
>


-

**Comment by magently** [comment]
-- Please reply above this line --


Hi,

Do you mean a reminder that the payment method is available only when
the order has EUR currency?

Best,
-- 
Monika Milewska,
Magently

**Comment by tilsammans** [comment]
Yep, so that the merchant is already warned. Just to make it very clear for them.

**Comment by tilsammans** [comment]
@magently did you complete this task?

**Comment by nicklloyd** [comment]
@tilsammans this can be closed:
https://github.com/Sign2Pay/magento-sign2pay/blob/fa8c3c5f32d341beed25a91331a637f443f995b2/app/code/community/Sign2pay/Payment/Block/Adminhtml/Notifications.php#L16

**Comment by tilsammans** [comment]
Thnx! Thought so.
